# Generated by Django 4.2.17 on 2025-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spycat",
            name="breed",
            field=models.CharField(
                choices=[
                    ("abyssinian", "Abyssinian"),
                    ("american_bobtail", "American Bobtail"),
                    ("american_curl", "American Curl"),
                    ("american_shorthair", "American Shorthair"),
                    ("balinese", "Balinese"),
                    ("bengal", "Bengal"),
                    ("birman", "Birman"),
                    ("bombay", "Bombay"),
                    ("british_shorthair", "British Shorthair"),
                    ("burmese", "Burmese"),
                    ("chartreux", "Chartreux"),
                    ("colorpoint_shorthair", "Colorpoint Shorthair"),
                    ("cornish_rex", "Cornish Rex"),
                    ("devon_rex", "Devon Rex"),
                    ("domestic_long_hair", "Domestic Long Hair"),
                    ("egyptian_mau", "Egyptian Mau"),
                    ("exotic_shorthair", "Exotic Shorthair"),
                    ("havana_brown", "Havana Brown"),
                    ("himalayan", "Himalayan"),
                    ("japanese_bobtail", "Japanese Bobtail"),
                    ("javanese", "Javanese"),
                    ("korat", "Korat"),
                    ("laperm", "LaPerm"),
                    ("maine_coon", "Maine Coon"),
                    ("manx", "Manx"),
                    ("norwegian_forest_cat", "Norwegian Forest Cat"),
                    ("ocicat", "Ocicat"),
                    ("oriental", "Oriental"),
                    ("persian", "Persian"),
                    ("ragamuffin", "RagaMuffin"),
                    ("ragdoll", "Ragdoll"),
                    ("russian_blue", "Russian Blue"),
                    ("scottish_fold", "Scottish Fold"),
                    ("selkirk_rex", "Selkirk Rex"),
                    ("siamese", "Siamese"),
                    ("siberian", "Siberian"),
                    ("singapura", "Singapura"),
                    ("somali", "Somali"),
                    ("sphynx", "Sphynx"),
                    ("tonkinese", "Tonkinese"),
                    ("turkish_angora", "Turkish Angora"),
                    ("turkish_van", "Turkish Van"),
                ],
                max_length=40,
                verbose_name="Breed",
            ),
        ),
        migrations.AlterField(
            model_name="spycat",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="target",
            unique_together={("id", "mission")},
        ),
    ]
