# Generated by Django 4.2.17 on 2025-06-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spy", "0002_alter_spycat_breed_alter_spycat_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="complete_state",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="name",
        ),
        migrations.RemoveField(
            model_name="target",
            name="complete_state",
        ),
        migrations.AddField(
            model_name="mission",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Mission Completed"),
        ),
        migrations.AddField(
            model_name="target",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Target Completed"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions",
                to="spy.spycat",
            ),
        ),
    ]
