# Generated by Django 4.2.17 on 2025-06-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spy", "0005_alter_mission_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions",
                to="spy.spycat",
            ),
        ),
    ]
