# Generated by Django 4.2.17 on 2025-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spy", "0006_alter_mission_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spycat",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="SpyCat Name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="target",
            unique_together={("name", "id", "mission")},
        ),
    ]
